# Generated by Django 2.2.6 on 2021-07-09 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Cena')),
                ('link', models.URLField(max_length=99, verbose_name='Link do produktu')),
                ('shop', models.CharField(choices=[('monter', 'Monter'), ('byggmax', 'Bygg Max'), ('optimera', 'Optimera'), ('jula', 'Jula'), ('clasohlson', 'Clas Ohlson'), ('biltema', 'Biltema'), ('jernia', 'Jernia'), ('obsbygg', 'OBS Bygg'), ('maxbo', 'MAXBO'), ('nysted', 'NySted'), ('flugger', 'Flügger')], default=1, max_length=64, verbose_name='Sklep')),
                ('priceFor', models.CharField(default='szt', max_length=15, verbose_name='Cena za')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_ev.Category', verbose_name='Kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa projektu')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='Ilość sztuk')),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena całkowita')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='price_ev.Products', verbose_name='Produkt')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_ev.Project', verbose_name='Projekt')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='product',
            field=models.ManyToManyField(through='price_ev.ProjectsProducts', to='price_ev.Products'),
        ),
    ]
