# Generated by Django 2.2.6 on 2021-07-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_ev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='shop',
            field=models.CharField(choices=[('nysted', 'NySted'), ('biltema', 'Biltema'), ('clasohlson', 'Clas Ohlson'), ('jula', 'Jula'), ('byggmax', 'Bygg Max'), ('optimera', 'Optimera'), ('jernia', 'Jernia'), ('obsbygg', 'OBS Bygg'), ('flugger', 'Flügger'), ('maxbo', 'MAXBO'), ('monter', 'Monter')], default=1, max_length=64, verbose_name='Sklep'),
        ),
        migrations.AlterUniqueTogether(
            name='projectsproducts',
            unique_together={('project', 'products')},
        ),
    ]
