# Generated by Django 2.2.6 on 2021-07-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_ev', '0002_auto_20210710_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=99, verbose_name='Link do produktu')),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='link',
        ),
        migrations.AlterField(
            model_name='products',
            name='shop',
            field=models.CharField(choices=[('flugger', 'Flügger'), ('jula', 'Jula'), ('clasohlson', 'Clas Ohlson'), ('optimera', 'Optimera'), ('byggmax', 'Bygg Max'), ('nysted', 'NySted'), ('maxbo', 'MAXBO'), ('jernia', 'Jernia'), ('obsbygg', 'OBS Bygg'), ('biltema', 'Biltema'), ('monter', 'Monter')], default=1, max_length=64, verbose_name='Sklep'),
        ),
    ]
