# Generated by Django 2.2.6 on 2021-07-14 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_ev', '0003_auto_20210714_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='price_ev.ProductLink', verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='products',
            name='shop',
            field=models.CharField(choices=[('jernia', 'Jernia'), ('nysted', 'NySted'), ('obsbygg', 'OBS Bygg'), ('monter', 'Monter'), ('maxbo', 'MAXBO'), ('biltema', 'Biltema'), ('jula', 'Jula'), ('clasohlson', 'Clas Ohlson'), ('byggmax', 'Bygg Max'), ('optimera', 'Optimera'), ('flugger', 'Flügger')], default=1, max_length=64, verbose_name='Sklep'),
        ),
    ]
