# Generated by Django 2.2.6 on 2021-07-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_ev', '0004_auto_20210714_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='link',
            field=models.URLField(max_length=99, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='products',
            name='shop',
            field=models.CharField(choices=[('jernia', 'Jernia'), ('optimera', 'Optimera'), ('jula', 'Jula'), ('obsbygg', 'OBS Bygg'), ('byggmax', 'Bygg Max'), ('clasohlson', 'Clas Ohlson'), ('nysted', 'NySted'), ('flugger', 'Flügger'), ('monter', 'Monter'), ('biltema', 'Biltema'), ('maxbo', 'MAXBO')], default=1, max_length=64, verbose_name='Sklep'),
        ),
        migrations.DeleteModel(
            name='ProductLink',
        ),
    ]
